service:
  name: department-service
# app and org for use with dashboard.serverless.com
# app: serverless-test
org: debanshus

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  profile: serverless
  region: us-east-1
  stackName: department-service-stack
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: ${cf:database-service-stack.DepartmentTableArn}

functions:
  insert:
    handler: src/handler.insert
    events:
      - http:
          path: insert
          method: post

  update:
    handler: src/handler.update
    events:
      - http:
          path: update
          method: put

  remove:
    handler: src/handler.remove
    events:
      - http:
          path: remove
          method: post

  get:
    handler: src/handler.get
    events:
      - http:
          path: get/{deptId}
          method: get

  getAll:
    handler: src/handler.getAll
    events:
      - http:
          path: getAll
          method: get
